### ISSUE TITLE
document 'while'

### ISSUE THREAD

**Issue by sneilan** [arohner/scriptjure#13]
This is a _slight_ problem. There's no way to create a loop at the moment. For now, I'll just use the quote operator:

user=> (js (quote "while (1) {") (alert "asdf") (quote "}"))
"while (1) {;\nalert(\"asdf\");\n};\n"

**Comment by arohner** [comment]
`while` already works, but is apparently not documented.

**Comment by sneilan** [comment]
OK, I'll see if maybe I can write some documentation for that.

**Comment by sneilan** [comment]
Oh wow! You're right, it does work. A while loop has the same syntax as any other function, therefore you can go like this:
(js (while (== a 5) (alert "asdf!")))
Which will print
"while ((a == 5)) { \nalert(\"asdf\");\n\n }"

**Comment by sneilan** [comment]
Definitely can't write for loops without the quote operator though:
user=> (js (for (var i 5) (<= i 5) (++ i)))
"var i;\nfor(i = 5;\n, (i <= 5), i++)"
